apiVersion: apps/v1
kind: Deployment
metadata:
  name: cicd-ice-front-deploy
  namespace: cicd-ice-coding
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: cicd-ice-coding
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cicd-ice-coding
    spec:
      containers:
        - name: cicd-ice-front
          image: woya031/ci-ice-front:1.2.7
          envFrom:
            - configMapRef:
                name: frontend-config
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cicd-ice-front-service
  namespace: cicd-ice-coding
spec:
  selector:
    app.kubernetes.io/name: cicd-ice-coding
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3000
